feat: implementa a função "candidatar à demanda logado no sistema"
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #100
Opened 2024-11-19 19:52 UTC by aliceabreu

- Quando o candidato clica no botão "quero ajudar" o formulário da candidatura já vem preenchido com os dados do voluntário e a demanda é atrelada ao seu perfil, podendo ser visualizada  na página Área do voluntário.

2024-11-19 22:20 UTC, gabrielrnascimento approved these changes

2024-11-19 22:20 UTC, gabrielrnascimento commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +function preencherFormulario(candidato) {
apenas um ponto no nome dessa função, todo o código está em inglês e esse nome em português acaba fugindo do padrão do resto do projeto

2024-11-20 00:05 UTC, aliceabreu commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +function preencherFormulario(candidato) {
Bem observado, Gabriel. Vou mudar :)

2024-11-20 01:53 UTC, DevDuque requested changes

2024-11-20 01:53 UTC, DevDuque commented on src/pages/candidatar-a-demanda/candidatar-a-demanda.js
> +function fillForm(candidato) {
![image](https://github.com/user-attachments/assets/349025e0-f1b9-46ca-b8d8-f958d0eb0f60)
Aqui está mudando o nome da ONG para o nome do candidato.

![image](https://github.com/user-attachments/assets/571c94be-b597-47af-a331-aab605904ece)

Estou Logado como Carlos, na hora de me candidatar, está puxando dados do Duque (Primeiro candidato criado nos testes).

Na edição de Perfil está funcionando normalmente

![image](https://github.com/user-attachments/assets/aa84166a-69dd-4f5d-a76b-f90b959bbb16)

2024-11-22 02:31 UTC, arondightt approved these changes

2024-11-24 18:24 UTC, merged