feat: funcionalidade de gerenciamento de conteúdos estáticos
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #102
Opened 2024-11-20 06:48 UTC by arondightt

Agora, o conteúdo das páginas estáticas é carregado dinamicamente a partir do DB.json. Também foi criado um novo usuário "admin" com permissão para editar esses conteúdos. Para acessar como admin, use o seguinte login na página de login:

Email: admin@admin.com  
Senha: 123456789

Antes de confirmar selecione a opção Entrar como "Administrador" que aparecera dinamicamente ao digitar "admin".
  
Ao logar como admin, um ícone de edição será exibido nas páginas.

2024-11-24 00:35 UTC, gabrielrnascimento approved these changes

2024-11-25 01:04 UTC, aliceabreu requested changes

2024-11-25 01:04 UTC, aliceabreu commented on src/components/header/header.js
> +                    <a id="pagina-do-admin" href=${getPagePath("pagina-do-admin")} class="header-button area-da-ong-button"><img class="dot-black" src="${rootPath}/assets/icons/dot-black.png">PÁGINA
Está com erro de digitação aqui "ADMININISTRADOR"

```suggestion
                    <a id="pagina-do-admin" href=${getPagePath("pagina-do-admin")} class="header-button area-da-ong-button"><img class="dot-black" src="${rootPath}/assets/icons/dot-black.png">PÁGINA DO ADMINISTRADOR</a>
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/pagina-do-admin/pagina-do-admin.html
> +                    Acesse as páginas informativas e clique no icone de editar para alterar as informações.
```suggestion
                    Acesse as páginas informativas e clique no ícone de editar para editar as informações.
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/pagina-do-admin/pagina-do-admin.html
> +                        <a href="../como-comecar/como-comecar.html"> como Começar?</a>
```suggestion
                        <a href="../como-comecar/como-comecar.html">Como começar?</a>
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/pagina-do-admin/pagina-do-admin.html
> +                        <a href="../sobre-o-voluntariado/sobre-o-voluntariado.html"> sobre o voluntariado</a>
```suggestion
                        <a href="../sobre-o-voluntariado/sobre-o-voluntariado.html">Sobre o voluntariado</a>
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/pagina-do-admin/pagina-do-admin.html
> +                        <a href="../por-que-ser-voluntario/por-que-ser-voluntario.html"> por que ser voluntario?</a>
```suggestion
                        <a href="../por-que-ser-voluntario/por-que-ser-voluntario.html">Por que ser voluntário?</a>
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/pagina-do-admin/pagina-do-admin.html
> +                        <a href="../perguntas-frequentes/perguntas-frequentes.html"> perguntas frequentes</a>
```suggestion
                        <a href="../perguntas-frequentes/perguntas-frequentes.html">Perguntas frequentes</a>
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/pagina-do-admin/pagina-do-admin.html
> +                        <a href="../historias-sucesso/historias-sucesso.html"> historias sucesso</a>
```suggestion
                        <a href="../historias-sucesso/historias-sucesso.html">Histórias de sucesso</a>
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/historias-sucesso/historias-sucesso.css
> +
Colocaria essas alterações para deixar a página menos colada na lateral.

![image](https://github.com/user-attachments/assets/be3c95ab-418c-4e85-8d70-d35eac9289f4)

```suggestion
    align-items: center;
    justify-content: space-between;
    margin-top: 20px;
    margin-bottom: 8%;
    margin-left: 8%;
    margin-right: 8%;
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/historias-sucesso/historias-sucesso.css
> +        justify-content: center;
Colocaria o ícone de editar embaixo para não quebrar o texto.

```suggestion
     display: flex;
    align-items: flex-start;
    flex-direction: column;
    justify-content: center;
    gap: 15px;
```

2024-11-25 01:04 UTC, aliceabreu commented on src/pages/historias-sucesso/historias-sucesso.css
>      text-align: left;
```suggestion
    text-align: justify;
```

2024-11-25 01:04 UTC, aliceabreu commented on src/css/informative-pages.css
> +}
Para centralizar o título.

```suggestion
align-content: center;
}
```

2024-11-25 21:48 UTC, aliceabreu approved these changes

2024-11-26 00:51 UTC, merged