Atualiza textos estado da arte, justificativa e referências.
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #15
Opened 2024-08-28 02:09 UTC by aliceabreu

2024-08-28 22:39 UTC, arondightt requested changes

2024-08-28 22:39 UTC, arondightt commented on docs/estado.md
> +É notável a importância da tecnologia em todos os setores da sociedade, e não é diferente para as Organizações Não Governamentais (ONGs). De acordo com Dias (2003)[[2]](../docs/referencias.md) o conc
acho que poderia mudar isso.

2024-08-28 22:41 UTC, gabrielrnascimento commented on docs/estado.md
> +A aplicação que será desenvolvida neste projeto tem relação com os trabalhos mencionado. Seu principal objetivo é conectar voluntários, entusiastas da tecnologia, com as ONGs, gerando um impacto soci
```suggestion
A aplicação que será desenvolvida neste projeto tem relação com os trabalhos mencionados. Seu principal objetivo é conectar voluntários, entusiastas da tecnologia, com as ONGs, gerando um impacto social para a comunidade. A finalidade dessa aplicação web é centralizar as organizações sociais do terceiro setor e suas demandas em apenas um lugar, facilitando com que os voluntários encontrem oportunidades que encaixem com seu perfil e nível de conhecimento.
```

- Adicionei um "s" no final de "mencionado"
- Removi a palavra "relevante" por conta do comentário do professor sobre não conseguirmos mensurar algo "relevante" ou "impactante"
- As outras mudanças eu achei que foram sugestões mesmo, mas nada importante 😊

2024-08-29 20:13 UTC, arondightt approved these changes

2024-08-29 22:47 UTC, gabrielrnascimento approved these changes

2024-08-30 23:10 UTC, merged