docs: define usuarios do sistema
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #25
Opened 2024-09-08 20:13 UTC by arondightt

Adicionando os usuários ''Representante da ONG'' e ''Voluntário de TI'' a documentação 3.3.3

2024-09-09 22:54 UTC, gabrielrnascimento approved these changes

2024-09-09 23:05 UTC, aliceabreu requested changes

2024-09-09 23:05 UTC, aliceabreu commented on docs/especificacao.md
> +| Voluntário de TI |	Usuário que oferece suas habilidades e conhecimentos em tecnologia para apoiar ONGs. Pode se inscrever em projetos, fornecer suporte técnico, desenvolver soluções para desafios e
- tecnologia para apoiar as ONGs.
- e compartilhar _feedback_ sobre sua experiência por meio de depoimentos.

Omar, sugeri algumas alterações gramaticais.

2024-09-10 00:39 UTC, arondightt commented on docs/especificacao.md
> +| Voluntário de TI |	Usuário que oferece suas habilidades e conhecimentos em tecnologia para apoiar ONGs. Pode se inscrever em projetos, fornecer suporte técnico, desenvolver soluções para desafios e
corrigido ✌️

2024-09-10 00:59 UTC, aliceabreu approved these changes

2024-09-16 20:12 UTC, merged