docs: adiciona requisitos funcionais
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #26
Opened 2024-09-09 22:52 UTC by aliceabreu

- Adiciona os requisitos funcionais do projeto.

2024-09-09 23:34 UTC, gabrielrnascimento requested changes

2024-09-09 23:34 UTC, gabrielrnascimento commented on docs/especificacao.md
> +| RF4 | A aplicação deve oferecer um processo de recuperação de senha. | O processo de recuperação de senha deve ser iniciado por meio de um link na tela de login, onde o usuário será solicitado a in
```suggestion
| RF4 | A aplicação deve oferecer um processo de recuperação de senha. | O processo de recuperação de senha deve ser iniciado por meio de um link na tela de login, onde o usuário será solicitado a informar o e-mail cadastrado. Após a submissão, o sistema deve enviar um e-mail contendo um link seguro para redefinição da senha. |
```

Atualmente o site não verifica nome de usuário para redefinição de senha, apenas e-mails, isso seria algo a ser adicionado no projeto?

2024-09-10 01:15 UTC, arondightt approved these changes

2024-09-10 02:18 UTC, gabrielrnascimento approved these changes

2024-09-16 02:01 UTC, merged