escopo 3.2.1 - 3.2.3
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #49
Opened 2024-09-25 10:57 UTC by LJ-Leonardo

Adicionando documentação correspondente ao 3.2.1 - 3.2.3

2024-09-25 23:41 UTC, gabrielrnascimento approved these changes

2024-09-25 23:41 UTC, gabrielrnascimento commented on docs/especificacao.md
> +* Módulo de Gerenciamento de Atividades: Permite que as ONGs publiquem oportunidades de voluntariado, e voluntários possam se inscrever em atividades específicas.
```suggestion
* Módulo de Gerenciamento de Demandas: Permite que as ONGs publiquem oportunidades de voluntariado, e voluntários possam se inscrever em atividades específicas.
```

Vamos chamar de demandas só para manter o padrão do projeto

2024-09-26 00:54 UTC, aliceabreu requested changes

2024-09-26 00:54 UTC, aliceabreu commented on docs/especificacao.md
> +Facilitar o encontro entre ONGs e profissionais que desejam atuar como voluntários, fornecendo uma plataforma de fácil utilização, que centraliza as necessidades das ONGs e as habilidades dos voluntá
Leo, acho que a palavra "encontro" não cabe muito bem aqui,  talvez colocar "conexão". 
E também não são só profissionais que podem se voluntariar. 

O que você acha? 

```suggestion
A missão do Conecta é facilitar a conexão entre ONGs e voluntários de tecnologia, fornecendo uma plataforma de fácil utilização, que centraliza as necessidades das ONGs e as habilidades dos voluntários, promovendo o impacto social positivo por meio do voluntariado.
```

2024-09-30 12:12 UTC, arondightt approved these changes

2024-09-30 21:52 UTC, merged