leonardo/csu4_csu11_pass_to_review
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #59
Opened 2024-10-01 12:39 UTC by LJ-Leonardo

Edição dos casos de uso 4 e 11 respectivamente.

2024-10-01 21:04 UTC, arondightt commented on docs/especificacao.md
> +**Sumário**: Este caso de uso permite que a ONG gerencie as informações do seu perfil no sistema. O objetivo principal é garantir que a ONG possa atualizar seus dados de contato, criar demandas para
acho que seria interessante apontar o representante da ONG como nosso usuário e não diretamente a ONG, o mesmo se repete em outras partes desse caso de uso
```suggestion
**Sumário**: Este caso de uso permite que o representante da ONG gerencie as informações do seu perfil no sistema. O objetivo principal é garantir que a ONG possa atualizar seus dados de contato, criar demandas para recrutar voluntários e acompanhar suas demandas e possíveis voluntários.
```

2024-10-01 21:07 UTC, arondightt commented on docs/especificacao.md
> +**Fluxo Principal**:Criar perfil da ONG
Em algumas partes acho que seria a ONG mesmo, como aqui no perfil, mas no que envolve quem é o usuário, seria "representante da ONG" mesmo.

2024-10-01 21:08 UTC, arondightt commented on docs/especificacao.md
> +**Fluxo Principal**:Criar perfil da ONG
Só ajustar o espaço
```suggestion
**Fluxo Principal**: Criar perfil da ONG.
```

2024-10-01 21:11 UTC, arondightt commented on docs/especificacao.md
> +**Ator Secundário**: Sistema.
não sei se entendi o Sistema como ator secundário, nesse caso não seria algo "Não existe."?

2024-10-01 22:29 UTC, LJ-Leonardo commented on docs/especificacao.md
> +**Ator Secundário**: Sistema.
imagino q seja o administrador usando o sistema apenas, para n deixar sem ator secundário entendi o sistema como um ator n?

2024-10-02 01:10 UTC, aliceabreu requested changes

2024-10-02 01:10 UTC, aliceabreu commented on docs/especificacao.md
> +**Ator Primário**: ONG.
Leo, aqui o ator seria Representante da ONG.

2024-10-02 01:10 UTC, aliceabreu commented on docs/especificacao.md
> +a) A ONG faz login no sistema e acessa a área de perfil. <br/>
Aqui também seria representante da ONG. Os atores são: representante da ONG, voluntário de TI, patrocinador e administrador.

Então tudo onde for função do ator seriam com esses nomes.

2024-10-02 01:10 UTC, aliceabreu commented on docs/especificacao.md
> +**Ator Secundário**: Sistema.
Isso aqui é "não existe". O sistema não é ator no caso.

2024-10-02 01:10 UTC, aliceabreu commented on docs/especificacao.md
Acho que aqui os fluxos alternativos poderiam ser 3: criar, editar e excluir.

2024-10-02 13:00 UTC, arondightt approved these changes

2024-10-02 13:00 UTC, arondightt commented on docs/especificacao.md
> +1)  A ONG acessa a página de cadastro do sistema.
Acho que tinha ficado  faltando só esse.
```suggestion
1)  O representante da ONG acessa a página de cadastro do sistema.
```

2024-10-02 23:13 UTC, gabrielrnascimento approved these changes

2024-10-02 23:18 UTC, aliceabreu approved these changes

2024-10-03 01:50 UTC, merged