Adiciona a prototipação do sistema com as imagens
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #82
Opened 2024-10-21 13:34 UTC by DevDuque

2024-10-21 16:17 UTC, gabrielrnascimento reviewed
Acho que faltou pontuar quais regras são aplicadas em cada uma das páginas, pelo que o professor comentou na reunião, esse ponto parece importante.

2024-10-21 22:29 UTC, gabrielrnascimento requested changes

2024-10-21 22:29 UTC, gabrielrnascimento commented on docs/design.md
> +### Leis de Gestalt
De acordo com o professor, não é necessário explicar as regras no documento.

2024-10-21 22:29 UTC, gabrielrnascimento commented on docs/design.md
> +## Prototipação do Projeto
De acordo com o professor é necessário:
- Dar uma breve explicação da página, o que ela faz, quais recursos estão disponíveis para o usuário...
- Qual/Quais regras de outro foram aplicadas na página

2024-10-24 13:05 UTC, DevDuque commented on docs/design.md
> +### Leis de Gestalt
Editei tudo aqui, se tiver mais sugestões. Só avisar que eu edito novamente!

2024-10-25 12:07 UTC, gabrielrnascimento approved these changes

2024-10-25 18:10 UTC, arondightt approved these changes

2024-10-26 01:04 UTC, merged