feat: implementa controle de acesso aos voluntarios
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #88
Opened 2024-11-01 22:33 UTC by gabrielrnascimento

- Implementa cadastro e login de voluntários
- Zerei o banco de dados `db.json` para testarmos tudo do zero
- Mantive os dados do antigo banco no arquivo `db.json.bak`

2024-11-02 23:16 UTC, arondightt commented
Logado com o candidato o caminho para Área do voluntario direciona para o pagina da ONG
![image](https://github.com/user-attachments/assets/095422fe-e3c6-4ab9-be4c-07f45927612b)

2024-11-02 23:58 UTC, arondightt commented on src/pages/login/login.js
> +        if(userType === "organization") {
![image](https://github.com/user-attachments/assets/6bf509b8-51d6-4310-aa13-dce4d4e2ade4)
ao fazer login continua na pagina de login

2024-11-02 23:58 UTC, arondightt commented on src/pages/pagina-do-voluntario/pagina-do-voluntario.js
> +    const task = new Task();
![image](https://github.com/user-attachments/assets/13ebc0e2-47d2-47da-9822-0747417d96fd)
a demanda aparece no perfil do candidato mesmo sem voluntariar

2024-11-02 23:58 UTC, arondightt commented on src/pages/pagina-do-voluntario/pagina-do-voluntario.js
> +    const task = new Task();
Logado com o candidato, clicar em Perfil leva a edição de perfil da ONG

2024-11-02 23:58 UTC, arondightt commented on src/components/header/header.js
>              <div class="buttons-header-wrapper">
![image](https://github.com/user-attachments/assets/77f99e0b-8c17-4f65-a071-1d5f2f2e0358)
Quando logado com a ONG, nao tem caminho para editar perfil da ONG.

2024-11-02 23:58 UTC, arondightt commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +            window.location.href = "../login/login.html";
![image](https://github.com/user-attachments/assets/c177da15-0e14-4dc0-85a5-f123566dd5e3)
ao cadastrar continua na pagina de cadastro, cadastrando ONG ou Voluntario

2024-11-03 18:37 UTC, gabrielrnascimento commented on src/pages/login/login.js
> +        if(userType === "organization") {
@arondightt esse eu não consegui reproduzir aqui, testei tanto com ong quanto voluntário 😕

2024-11-04 22:11 UTC, gabrielrnascimento commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +            window.location.href = "../login/login.html";
também não consegui reproduzir esse bug

2024-11-04 23:04 UTC, arondightt requested changes
![image](https://github.com/user-attachments/assets/b5d5d9b1-f528-4a20-9767-8e786515546e)
ao clicar para editar o perfil do voluntario não carrega as informações ja existentes.

2024-11-04 23:04 UTC, arondightt commented on src/pages/administrar-demandas/administrar-demandas.js
>                  `<div class="vertical-task-card" onclick="modal($(this), event);">`+
![image](https://github.com/user-attachments/assets/5da65f1f-16a4-4eba-a1e6-eef38ca00fcb)
A demanda recebe todos os usuários cadastrado para aprovação, mesmo sem se candidatar.

2024-11-05 23:43 UTC, gabrielrnascimento commented on src/pages/administrar-demandas/administrar-demandas.js
>                  `<div class="vertical-task-card" onclick="modal($(this), event);">`+
corrigido

2024-11-06 02:33 UTC, aliceabreu commented
![m575sjyl](https://github.com/user-attachments/assets/c65b06f0-f78f-4b78-a47d-b1752505b054)


Gabriel, o botão aqui poderia ser "Salvar". Porque parece que vai editar de novo, sem salvar nada antes.

2024-11-06 02:34 UTC, aliceabreu commented
![image](https://github.com/user-attachments/assets/0c3be18d-e5d6-4c9b-9cc8-d8b8e04dde0a)

Nessa mesma página não está salvando as alterações do voluntário depois de alteradas. Mudei meu nome e não salvou.

2024-11-06 02:37 UTC, aliceabreu commented
![image](https://github.com/user-attachments/assets/4e925278-1750-47c5-85ae-e00e65fb2534)

Na página de login seria interessante se o usuário pudesse escolher primeiro se é ONG ou voluntário para depois entrar com as informações de e-mail e senha, ou seja, "Entrar como" poderia estar em cima, antes de e-mail e senha.

2024-11-06 02:39 UTC, aliceabreu commented
Só para registrar aqui,  as páginas de Cadastrar Voluntário e Login não estão sendo redirecionadas, respectivamente, para: "Login" e "Área do Voluntário".

2024-11-06 02:48 UTC, aliceabreu commented
![image](https://github.com/user-attachments/assets/a6313261-1150-46d6-8cda-826db519df2f)

![image](https://github.com/user-attachments/assets/726adc0b-5064-4d58-9e38-a36d931e4ba1)

![image](https://github.com/user-attachments/assets/d8fad775-65cf-4f66-a817-7dcd8d1a03a4)

Quando faço o cadastro da ONG, coloco as informações na primeira página, clico no botão "PRÓXIMO", depois clico no botão "VOLTAR" os dados inseridos na primeira página não aparecem mais.

2024-11-06 03:09 UTC, aliceabreu requested changes

2024-11-06 03:09 UTC, aliceabreu commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +        document.getElementById("submit-button").value = "Editar";
![m575sjyl](https://github.com/user-attachments/assets/c65b06f0-f78f-4b78-a47d-b1752505b054)


Gabriel, o botão aqui poderia ser "Salvar". Porque parece que vai editar de novo, sem salvar nada antes.

2024-11-06 03:09 UTC, aliceabreu commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +        document.getElementById("submit-button").value = "Editar";
![image](https://github.com/user-attachments/assets/0c3be18d-e5d6-4c9b-9cc8-d8b8e04dde0a)

Nessa mesma página não está salvando os dados do voluntário depois de alterados. Mudei meu nome e não salvou.

2024-11-06 03:09 UTC, aliceabreu commented on src/pages/login/login.html
> +                        <label>Entrar como:</label>
![image](https://github.com/user-attachments/assets/4e925278-1750-47c5-85ae-e00e65fb2534)

Na página de login seria interessante se o usuário pudesse escolher primeiro se é ONG ou voluntário para depois entrar com as informações de e-mail e senha, ou seja, "Entrar como" poderia estar em cima, antes de e-mail e senha.

2024-11-06 03:09 UTC, aliceabreu commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +            window.location.href = "../login/login.html";
Só para registrar aqui, as páginas de Cadastrar Voluntário e Login não estão sendo redirecionadas, respectivamente, para: "Login" e "Área do Voluntário".

2024-11-06 03:09 UTC, aliceabreu commented on src/pages/cadastrar-ong/cadastrar-ong-1.js
> +    }
![image](https://github.com/user-attachments/assets/a6313261-1150-46d6-8cda-826db519df2f)

![image](https://github.com/user-attachments/assets/726adc0b-5064-4d58-9e38-a36d931e4ba1)

![image](https://github.com/user-attachments/assets/d8fad775-65cf-4f66-a817-7dcd8d1a03a4)

Quando faço o cadastro da ONG, coloco as informações na primeira página, clico no botão "PRÓXIMO", depois clico no botão "VOLTAR" os dados inseridos na primeira página não aparecem mais.

2024-11-06 03:14 UTC, arondightt commented on src/pages/cadastrar-ong/cadastrar-ong-1.js
> +    }
isso aqui acho que é ta sendo direcionado pelo html, na linha 78 do arquivo cadastrar-ong-2.html  esta               
 ` <div><a href="cadastrar-ong-1.html"><input type="submit" name="voltar" value="Voltar"></a></div>`
se trocar para               
 ` <div><input type="submit" name="voltar" value="Voltar" onclick="history.go(-1)"></div>`
resolve

2024-11-06 23:36 UTC, gabrielrnascimento commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +        document.getElementById("submit-button").value = "Editar";
feito

2024-11-06 23:44 UTC, gabrielrnascimento commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +        document.getElementById("submit-button").value = "Editar";
corrigido

2024-11-06 23:47 UTC, gabrielrnascimento commented on src/pages/login/login.html
> +                        <label>Entrar como:</label>
feito

2024-11-08 02:02 UTC, arondightt approved these changes

2024-11-09 17:51 UTC, gabrielrnascimento commented on src/pages/cadastrar-ong/cadastrar-ong-1.js
> +    }
valeu @arondightt, resolveu mesmo!

2024-11-09 17:51 UTC, gabrielrnascimento commented on src/pages/cadastrar-ong/cadastrar-ong-1.js
> +    }
@aliceabreu pode conferir, por favor?

2024-11-09 18:23 UTC, gabrielrnascimento commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +            window.location.href = "../login/login.html";
consegui reproduzir e corrigi agora

2024-11-09 18:23 UTC, gabrielrnascimento commented on src/pages/login/login.js
> +        if(userType === "organization") {
@arondightt corrigido

2024-11-09 18:23 UTC, gabrielrnascimento commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +            window.location.href = "../login/login.html";
@aliceabreu consegui corrigir tanto para ong quanto para voluntário

2024-11-09 19:08 UTC, arondightt commented on src/pages/login/login.js
> +        if(userType === "organization") {
aqui ao fazer login ou cadastrar demanda  apenas atualiza a pagina, não redireciona

2024-11-09 19:11 UTC, arondightt commented on src/pages/cadastrar-voluntario/cadastrar-voluntario.js
> +            window.location.href = "../login/login.html";
tks

2024-11-09 19:16 UTC, arondightt approved these changes

2024-11-09 21:56 UTC, aliceabreu approved these changes

2024-11-09 21:56 UTC, aliceabreu commented on src/components/header/header.js
>                  <a id="logout-click" style="${token == null ? "display: none" : ""}" id="logout-click" href="#" class="header-button area-da-ong-button"><img class="log-out" src="${rootPath}/assets/i
Gabriel, quando clica em SAIR, acho que poderia redirecionar para a Landing Page.

2024-11-09 21:56 UTC, aliceabreu commented on src/pages/cadastrar-ong/cadastrar-ong-1.js
> +    }
Certinho! Boa Gabriel!

2024-11-11 22:22 UTC, merged