Adiciona o público alvo (Profissionais e ONGs)
ICEI-PUC-Minas-PMV-SI/pmv-si-2024-2-pe3-t1-grupo-4 pull request #9
Opened 2024-08-13 13:54 UTC by DevDuque

2024-08-16 18:56 UTC, gabrielrnascimento approved these changes

2024-08-16 18:56 UTC, gabrielrnascimento commented on docs/introducao.md
> +- **Falta de recursos técnicos:** Muitas ONGs não dispõem de profissionais capacitados internamente para implementar e manter sistemas tecnológicos eficazes.
acho que aqui poderia ser algo como "voluntários com conhecimento técnico" ou algo do tipo

2024-08-16 19:17 UTC, aliceabreu commented on docs/introducao.md
>  ## 1.1. Problema
Davih, acredito que aqui o texto pode ser mais sucinto, sem muito uso dos bullet points, para deixar o texto mais fluído.

2024-08-21 23:11 UTC, aliceabreu approved these changes

2024-08-22 01:48 UTC, arondightt requested changes

2024-08-22 01:48 UTC, arondightt commented on docs/introducao.md
>  ## 1.1. Problema
Concordo, o professor sugeriu um paragrafo simples e deixou como exemplo dessa forma, também acho que ficaria melhor sem os  bullets como aqui:
![2024-08-21 à(s) 22 28 29_03bad903](https://github.com/user-attachments/assets/7722920a-c164-4a05-802e-200e2dc480b2)

2024-08-22 01:48 UTC, arondightt commented on docs/introducao.md
> +
a mesma questão dos bullets , acredito que um paragrafo bem estruturado poderia ser bem informativo e simples para o entendimento
![2024-08-21 à(s) 22 32 35_86539f3d](https://github.com/user-attachments/assets/88ed802f-6c33-4df3-bbf7-da86a9d62cd9)

2024-08-22 02:04 UTC, aliceabreu commented on docs/introducao.md
> +
Acho que aqui não precisa fazer essa divisão, para não limitar os voluntários. Qualquer um que tenha capacidade e entendimento pode se voluntariar. Poderia generalizar, todos os entusiastas de tecnologia, estudantes, profissionais etc.

2024-08-22 02:07 UTC, aliceabreu commented on docs/introducao.md
Aqui também não precisa dividir, porque as ONGs são muito diversificadas. Os trabalhos que elas podem solicitar com relação à tecnologia podem ser diversos, não somente ajuda técnica.

2024-08-26 05:42 UTC, arondightt approved these changes

2024-08-26 23:52 UTC, merged